# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nawawy/CLionProjects/Final?/distributed_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nawawy/CLionProjects/Final?/distributed_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nawawy/CLionProjects/Final?/distributed_2/CMakeFiles /home/nawawy/CLionProjects/Final?/distributed_2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nawawy/CLionProjects/Final?/distributed_2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named centralserver

# Build rule for target.
centralserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 centralserver
.PHONY : centralserver

# fast build rule for target.
centralserver/fast:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/build
.PHONY : centralserver/fast

#=============================================================================
# Target rules for targets named application

# Build rule for target.
application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application
.PHONY : application

# fast build rule for target.
application/fast:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/build
.PHONY : application/fast

#=============================================================================
# Target rules for targets named centralserver_automoc

# Build rule for target.
centralserver_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 centralserver_automoc
.PHONY : centralserver_automoc

# fast build rule for target.
centralserver_automoc/fast:
	$(MAKE) -f CMakeFiles/centralserver_automoc.dir/build.make CMakeFiles/centralserver_automoc.dir/build
.PHONY : centralserver_automoc/fast

#=============================================================================
# Target rules for targets named application_automoc

# Build rule for target.
application_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application_automoc
.PHONY : application_automoc

# fast build rule for target.
application_automoc/fast:
	$(MAKE) -f CMakeFiles/application_automoc.dir/build.make CMakeFiles/application_automoc.dir/build
.PHONY : application_automoc/fast

ApplicationStart.o: ApplicationStart.cpp.o

.PHONY : ApplicationStart.o

# target to build an object file
ApplicationStart.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/ApplicationStart.cpp.o
.PHONY : ApplicationStart.cpp.o

ApplicationStart.i: ApplicationStart.cpp.i

.PHONY : ApplicationStart.i

# target to preprocess a source file
ApplicationStart.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/ApplicationStart.cpp.i
.PHONY : ApplicationStart.cpp.i

ApplicationStart.s: ApplicationStart.cpp.s

.PHONY : ApplicationStart.s

# target to generate assembly for a file
ApplicationStart.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/ApplicationStart.cpp.s
.PHONY : ApplicationStart.cpp.s

AuthenticationServer.o: AuthenticationServer.cpp.o

.PHONY : AuthenticationServer.o

# target to build an object file
AuthenticationServer.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/AuthenticationServer.cpp.o
.PHONY : AuthenticationServer.cpp.o

AuthenticationServer.i: AuthenticationServer.cpp.i

.PHONY : AuthenticationServer.i

# target to preprocess a source file
AuthenticationServer.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/AuthenticationServer.cpp.i
.PHONY : AuthenticationServer.cpp.i

AuthenticationServer.s: AuthenticationServer.cpp.s

.PHONY : AuthenticationServer.s

# target to generate assembly for a file
AuthenticationServer.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/AuthenticationServer.cpp.s
.PHONY : AuthenticationServer.cpp.s

CustomObjects/CustomBool.o: CustomObjects/CustomBool.cpp.o

.PHONY : CustomObjects/CustomBool.o

# target to build an object file
CustomObjects/CustomBool.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomBool.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomBool.cpp.o
.PHONY : CustomObjects/CustomBool.cpp.o

CustomObjects/CustomBool.i: CustomObjects/CustomBool.cpp.i

.PHONY : CustomObjects/CustomBool.i

# target to preprocess a source file
CustomObjects/CustomBool.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomBool.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomBool.cpp.i
.PHONY : CustomObjects/CustomBool.cpp.i

CustomObjects/CustomBool.s: CustomObjects/CustomBool.cpp.s

.PHONY : CustomObjects/CustomBool.s

# target to generate assembly for a file
CustomObjects/CustomBool.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomBool.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomBool.cpp.s
.PHONY : CustomObjects/CustomBool.cpp.s

CustomObjects/CustomInt.o: CustomObjects/CustomInt.cpp.o

.PHONY : CustomObjects/CustomInt.o

# target to build an object file
CustomObjects/CustomInt.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomInt.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomInt.cpp.o
.PHONY : CustomObjects/CustomInt.cpp.o

CustomObjects/CustomInt.i: CustomObjects/CustomInt.cpp.i

.PHONY : CustomObjects/CustomInt.i

# target to preprocess a source file
CustomObjects/CustomInt.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomInt.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomInt.cpp.i
.PHONY : CustomObjects/CustomInt.cpp.i

CustomObjects/CustomInt.s: CustomObjects/CustomInt.cpp.s

.PHONY : CustomObjects/CustomInt.s

# target to generate assembly for a file
CustomObjects/CustomInt.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomInt.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomInt.cpp.s
.PHONY : CustomObjects/CustomInt.cpp.s

CustomObjects/CustomMap.o: CustomObjects/CustomMap.cpp.o

.PHONY : CustomObjects/CustomMap.o

# target to build an object file
CustomObjects/CustomMap.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomMap.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomMap.cpp.o
.PHONY : CustomObjects/CustomMap.cpp.o

CustomObjects/CustomMap.i: CustomObjects/CustomMap.cpp.i

.PHONY : CustomObjects/CustomMap.i

# target to preprocess a source file
CustomObjects/CustomMap.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomMap.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomMap.cpp.i
.PHONY : CustomObjects/CustomMap.cpp.i

CustomObjects/CustomMap.s: CustomObjects/CustomMap.cpp.s

.PHONY : CustomObjects/CustomMap.s

# target to generate assembly for a file
CustomObjects/CustomMap.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomMap.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomMap.cpp.s
.PHONY : CustomObjects/CustomMap.cpp.s

CustomObjects/CustomString.o: CustomObjects/CustomString.cpp.o

.PHONY : CustomObjects/CustomString.o

# target to build an object file
CustomObjects/CustomString.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomString.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomString.cpp.o
.PHONY : CustomObjects/CustomString.cpp.o

CustomObjects/CustomString.i: CustomObjects/CustomString.cpp.i

.PHONY : CustomObjects/CustomString.i

# target to preprocess a source file
CustomObjects/CustomString.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomString.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomString.cpp.i
.PHONY : CustomObjects/CustomString.cpp.i

CustomObjects/CustomString.s: CustomObjects/CustomString.cpp.s

.PHONY : CustomObjects/CustomString.s

# target to generate assembly for a file
CustomObjects/CustomString.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomString.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomString.cpp.s
.PHONY : CustomObjects/CustomString.cpp.s

CustomObjects/CustomVector.o: CustomObjects/CustomVector.cpp.o

.PHONY : CustomObjects/CustomVector.o

# target to build an object file
CustomObjects/CustomVector.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomVector.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomVector.cpp.o
.PHONY : CustomObjects/CustomVector.cpp.o

CustomObjects/CustomVector.i: CustomObjects/CustomVector.cpp.i

.PHONY : CustomObjects/CustomVector.i

# target to preprocess a source file
CustomObjects/CustomVector.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomVector.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomVector.cpp.i
.PHONY : CustomObjects/CustomVector.cpp.i

CustomObjects/CustomVector.s: CustomObjects/CustomVector.cpp.s

.PHONY : CustomObjects/CustomVector.s

# target to generate assembly for a file
CustomObjects/CustomVector.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/CustomObjects/CustomVector.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/CustomObjects/CustomVector.cpp.s
.PHONY : CustomObjects/CustomVector.cpp.s

Database/DatabaseHandler.o: Database/DatabaseHandler.cpp.o

.PHONY : Database/DatabaseHandler.o

# target to build an object file
Database/DatabaseHandler.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Database/DatabaseHandler.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Database/DatabaseHandler.cpp.o
.PHONY : Database/DatabaseHandler.cpp.o

Database/DatabaseHandler.i: Database/DatabaseHandler.cpp.i

.PHONY : Database/DatabaseHandler.i

# target to preprocess a source file
Database/DatabaseHandler.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Database/DatabaseHandler.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Database/DatabaseHandler.cpp.i
.PHONY : Database/DatabaseHandler.cpp.i

Database/DatabaseHandler.s: Database/DatabaseHandler.cpp.s

.PHONY : Database/DatabaseHandler.s

# target to generate assembly for a file
Database/DatabaseHandler.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Database/DatabaseHandler.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Database/DatabaseHandler.cpp.s
.PHONY : Database/DatabaseHandler.cpp.s

Marshalling/MarshalledMessage.o: Marshalling/MarshalledMessage.cpp.o

.PHONY : Marshalling/MarshalledMessage.o

# target to build an object file
Marshalling/MarshalledMessage.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Marshalling/MarshalledMessage.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Marshalling/MarshalledMessage.cpp.o
.PHONY : Marshalling/MarshalledMessage.cpp.o

Marshalling/MarshalledMessage.i: Marshalling/MarshalledMessage.cpp.i

.PHONY : Marshalling/MarshalledMessage.i

# target to preprocess a source file
Marshalling/MarshalledMessage.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Marshalling/MarshalledMessage.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Marshalling/MarshalledMessage.cpp.i
.PHONY : Marshalling/MarshalledMessage.cpp.i

Marshalling/MarshalledMessage.s: Marshalling/MarshalledMessage.cpp.s

.PHONY : Marshalling/MarshalledMessage.s

# target to generate assembly for a file
Marshalling/MarshalledMessage.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Marshalling/MarshalledMessage.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Marshalling/MarshalledMessage.cpp.s
.PHONY : Marshalling/MarshalledMessage.cpp.s

Marshalling/MarshallingManager.o: Marshalling/MarshallingManager.cpp.o

.PHONY : Marshalling/MarshallingManager.o

# target to build an object file
Marshalling/MarshallingManager.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Marshalling/MarshallingManager.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Marshalling/MarshallingManager.cpp.o
.PHONY : Marshalling/MarshallingManager.cpp.o

Marshalling/MarshallingManager.i: Marshalling/MarshallingManager.cpp.i

.PHONY : Marshalling/MarshallingManager.i

# target to preprocess a source file
Marshalling/MarshallingManager.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Marshalling/MarshallingManager.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Marshalling/MarshallingManager.cpp.i
.PHONY : Marshalling/MarshallingManager.cpp.i

Marshalling/MarshallingManager.s: Marshalling/MarshallingManager.cpp.s

.PHONY : Marshalling/MarshallingManager.s

# target to generate assembly for a file
Marshalling/MarshallingManager.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/Marshalling/MarshallingManager.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Marshalling/MarshallingManager.cpp.s
.PHONY : Marshalling/MarshallingManager.cpp.s

Pages/HomePage.o: Pages/HomePage.cpp.o

.PHONY : Pages/HomePage.o

# target to build an object file
Pages/HomePage.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Pages/HomePage.cpp.o
.PHONY : Pages/HomePage.cpp.o

Pages/HomePage.i: Pages/HomePage.cpp.i

.PHONY : Pages/HomePage.i

# target to preprocess a source file
Pages/HomePage.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Pages/HomePage.cpp.i
.PHONY : Pages/HomePage.cpp.i

Pages/HomePage.s: Pages/HomePage.cpp.s

.PHONY : Pages/HomePage.s

# target to generate assembly for a file
Pages/HomePage.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Pages/HomePage.cpp.s
.PHONY : Pages/HomePage.cpp.s

Pages/LoginPage.o: Pages/LoginPage.cpp.o

.PHONY : Pages/LoginPage.o

# target to build an object file
Pages/LoginPage.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Pages/LoginPage.cpp.o
.PHONY : Pages/LoginPage.cpp.o

Pages/LoginPage.i: Pages/LoginPage.cpp.i

.PHONY : Pages/LoginPage.i

# target to preprocess a source file
Pages/LoginPage.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Pages/LoginPage.cpp.i
.PHONY : Pages/LoginPage.cpp.i

Pages/LoginPage.s: Pages/LoginPage.cpp.s

.PHONY : Pages/LoginPage.s

# target to generate assembly for a file
Pages/LoginPage.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Pages/LoginPage.cpp.s
.PHONY : Pages/LoginPage.cpp.s

RPC/RpcCallsAuthServer.o: RPC/RpcCallsAuthServer.cpp.o

.PHONY : RPC/RpcCallsAuthServer.o

# target to build an object file
RPC/RpcCallsAuthServer.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RPC/RpcCallsAuthServer.cpp.o
.PHONY : RPC/RpcCallsAuthServer.cpp.o

RPC/RpcCallsAuthServer.i: RPC/RpcCallsAuthServer.cpp.i

.PHONY : RPC/RpcCallsAuthServer.i

# target to preprocess a source file
RPC/RpcCallsAuthServer.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RPC/RpcCallsAuthServer.cpp.i
.PHONY : RPC/RpcCallsAuthServer.cpp.i

RPC/RpcCallsAuthServer.s: RPC/RpcCallsAuthServer.cpp.s

.PHONY : RPC/RpcCallsAuthServer.s

# target to generate assembly for a file
RPC/RpcCallsAuthServer.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RPC/RpcCallsAuthServer.cpp.s
.PHONY : RPC/RpcCallsAuthServer.cpp.s

RPC/RpcCallsClient.o: RPC/RpcCallsClient.cpp.o

.PHONY : RPC/RpcCallsClient.o

# target to build an object file
RPC/RpcCallsClient.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcCallsClient.cpp.o
.PHONY : RPC/RpcCallsClient.cpp.o

RPC/RpcCallsClient.i: RPC/RpcCallsClient.cpp.i

.PHONY : RPC/RpcCallsClient.i

# target to preprocess a source file
RPC/RpcCallsClient.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcCallsClient.cpp.i
.PHONY : RPC/RpcCallsClient.cpp.i

RPC/RpcCallsClient.s: RPC/RpcCallsClient.cpp.s

.PHONY : RPC/RpcCallsClient.s

# target to generate assembly for a file
RPC/RpcCallsClient.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcCallsClient.cpp.s
.PHONY : RPC/RpcCallsClient.cpp.s

RPC/RpcCallsServer.o: RPC/RpcCallsServer.cpp.o

.PHONY : RPC/RpcCallsServer.o

# target to build an object file
RPC/RpcCallsServer.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcCallsServer.cpp.o
.PHONY : RPC/RpcCallsServer.cpp.o

RPC/RpcCallsServer.i: RPC/RpcCallsServer.cpp.i

.PHONY : RPC/RpcCallsServer.i

# target to preprocess a source file
RPC/RpcCallsServer.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcCallsServer.cpp.i
.PHONY : RPC/RpcCallsServer.cpp.i

RPC/RpcCallsServer.s: RPC/RpcCallsServer.cpp.s

.PHONY : RPC/RpcCallsServer.s

# target to generate assembly for a file
RPC/RpcCallsServer.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcCallsServer.cpp.s
.PHONY : RPC/RpcCallsServer.cpp.s

RPC/RpcStubAuthServer.o: RPC/RpcStubAuthServer.cpp.o

.PHONY : RPC/RpcStubAuthServer.o

# target to build an object file
RPC/RpcStubAuthServer.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RPC/RpcStubAuthServer.cpp.o
.PHONY : RPC/RpcStubAuthServer.cpp.o

RPC/RpcStubAuthServer.i: RPC/RpcStubAuthServer.cpp.i

.PHONY : RPC/RpcStubAuthServer.i

# target to preprocess a source file
RPC/RpcStubAuthServer.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RPC/RpcStubAuthServer.cpp.i
.PHONY : RPC/RpcStubAuthServer.cpp.i

RPC/RpcStubAuthServer.s: RPC/RpcStubAuthServer.cpp.s

.PHONY : RPC/RpcStubAuthServer.s

# target to generate assembly for a file
RPC/RpcStubAuthServer.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RPC/RpcStubAuthServer.cpp.s
.PHONY : RPC/RpcStubAuthServer.cpp.s

RPC/RpcStubServer.o: RPC/RpcStubServer.cpp.o

.PHONY : RPC/RpcStubServer.o

# target to build an object file
RPC/RpcStubServer.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcStubServer.cpp.o
.PHONY : RPC/RpcStubServer.cpp.o

RPC/RpcStubServer.i: RPC/RpcStubServer.cpp.i

.PHONY : RPC/RpcStubServer.i

# target to preprocess a source file
RPC/RpcStubServer.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcStubServer.cpp.i
.PHONY : RPC/RpcStubServer.cpp.i

RPC/RpcStubServer.s: RPC/RpcStubServer.cpp.s

.PHONY : RPC/RpcStubServer.s

# target to generate assembly for a file
RPC/RpcStubServer.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RPC/RpcStubServer.cpp.s
.PHONY : RPC/RpcStubServer.cpp.s

RequestHandler.o: RequestHandler.cpp.o

.PHONY : RequestHandler.o

# target to build an object file
RequestHandler.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RequestHandler.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RequestHandler.cpp.o
.PHONY : RequestHandler.cpp.o

RequestHandler.i: RequestHandler.cpp.i

.PHONY : RequestHandler.i

# target to preprocess a source file
RequestHandler.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RequestHandler.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RequestHandler.cpp.i
.PHONY : RequestHandler.cpp.i

RequestHandler.s: RequestHandler.cpp.s

.PHONY : RequestHandler.s

# target to generate assembly for a file
RequestHandler.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/RequestHandler.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/RequestHandler.cpp.s
.PHONY : RequestHandler.cpp.s

Stegnography/Paths.o: Stegnography/Paths.cpp.o

.PHONY : Stegnography/Paths.o

# target to build an object file
Stegnography/Paths.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Stegnography/Paths.cpp.o
.PHONY : Stegnography/Paths.cpp.o

Stegnography/Paths.i: Stegnography/Paths.cpp.i

.PHONY : Stegnography/Paths.i

# target to preprocess a source file
Stegnography/Paths.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Stegnography/Paths.cpp.i
.PHONY : Stegnography/Paths.cpp.i

Stegnography/Paths.s: Stegnography/Paths.cpp.s

.PHONY : Stegnography/Paths.s

# target to generate assembly for a file
Stegnography/Paths.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Stegnography/Paths.cpp.s
.PHONY : Stegnography/Paths.cpp.s

Stegnography/StegManager.o: Stegnography/StegManager.cpp.o

.PHONY : Stegnography/StegManager.o

# target to build an object file
Stegnography/StegManager.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Stegnography/StegManager.cpp.o
.PHONY : Stegnography/StegManager.cpp.o

Stegnography/StegManager.i: Stegnography/StegManager.cpp.i

.PHONY : Stegnography/StegManager.i

# target to preprocess a source file
Stegnography/StegManager.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Stegnography/StegManager.cpp.i
.PHONY : Stegnography/StegManager.cpp.i

Stegnography/StegManager.s: Stegnography/StegManager.cpp.s

.PHONY : Stegnography/StegManager.s

# target to generate assembly for a file
Stegnography/StegManager.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/Stegnography/StegManager.cpp.s
.PHONY : Stegnography/StegManager.cpp.s

UDPLayer/Message.o: UDPLayer/Message.cpp.o

.PHONY : UDPLayer/Message.o

# target to build an object file
UDPLayer/Message.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/Message.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/Message.cpp.o
.PHONY : UDPLayer/Message.cpp.o

UDPLayer/Message.i: UDPLayer/Message.cpp.i

.PHONY : UDPLayer/Message.i

# target to preprocess a source file
UDPLayer/Message.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/Message.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/Message.cpp.i
.PHONY : UDPLayer/Message.cpp.i

UDPLayer/Message.s: UDPLayer/Message.cpp.s

.PHONY : UDPLayer/Message.s

# target to generate assembly for a file
UDPLayer/Message.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/Message.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/Message.cpp.s
.PHONY : UDPLayer/Message.cpp.s

UDPLayer/MySocket.o: UDPLayer/MySocket.cpp.o

.PHONY : UDPLayer/MySocket.o

# target to build an object file
UDPLayer/MySocket.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/MySocket.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/MySocket.cpp.o
.PHONY : UDPLayer/MySocket.cpp.o

UDPLayer/MySocket.i: UDPLayer/MySocket.cpp.i

.PHONY : UDPLayer/MySocket.i

# target to preprocess a source file
UDPLayer/MySocket.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/MySocket.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/MySocket.cpp.i
.PHONY : UDPLayer/MySocket.cpp.i

UDPLayer/MySocket.s: UDPLayer/MySocket.cpp.s

.PHONY : UDPLayer/MySocket.s

# target to generate assembly for a file
UDPLayer/MySocket.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/MySocket.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/MySocket.cpp.s
.PHONY : UDPLayer/MySocket.cpp.s

UDPLayer/UDPSocket.o: UDPLayer/UDPSocket.cpp.o

.PHONY : UDPLayer/UDPSocket.o

# target to build an object file
UDPLayer/UDPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/UDPSocket.cpp.o
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/UDPSocket.cpp.o
.PHONY : UDPLayer/UDPSocket.cpp.o

UDPLayer/UDPSocket.i: UDPLayer/UDPSocket.cpp.i

.PHONY : UDPLayer/UDPSocket.i

# target to preprocess a source file
UDPLayer/UDPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/UDPSocket.cpp.i
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/UDPSocket.cpp.i
.PHONY : UDPLayer/UDPSocket.cpp.i

UDPLayer/UDPSocket.s: UDPLayer/UDPSocket.cpp.s

.PHONY : UDPLayer/UDPSocket.s

# target to generate assembly for a file
UDPLayer/UDPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/UDPLayer/UDPSocket.cpp.s
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/UDPLayer/UDPSocket.cpp.s
.PHONY : UDPLayer/UDPSocket.cpp.s

application_automoc.o: application_automoc.cpp.o

.PHONY : application_automoc.o

# target to build an object file
application_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/application_automoc.cpp.o
.PHONY : application_automoc.cpp.o

application_automoc.i: application_automoc.cpp.i

.PHONY : application_automoc.i

# target to preprocess a source file
application_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/application_automoc.cpp.i
.PHONY : application_automoc.cpp.i

application_automoc.s: application_automoc.cpp.s

.PHONY : application_automoc.s

# target to generate assembly for a file
application_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/application_automoc.cpp.s
.PHONY : application_automoc.cpp.s

centralserver_automoc.o: centralserver_automoc.cpp.o

.PHONY : centralserver_automoc.o

# target to build an object file
centralserver_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/centralserver_automoc.cpp.o
.PHONY : centralserver_automoc.cpp.o

centralserver_automoc.i: centralserver_automoc.cpp.i

.PHONY : centralserver_automoc.i

# target to preprocess a source file
centralserver_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/centralserver_automoc.cpp.i
.PHONY : centralserver_automoc.cpp.i

centralserver_automoc.s: centralserver_automoc.cpp.s

.PHONY : centralserver_automoc.s

# target to generate assembly for a file
centralserver_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/centralserver.dir/build.make CMakeFiles/centralserver.dir/centralserver_automoc.cpp.s
.PHONY : centralserver_automoc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... centralserver"
	@echo "... application"
	@echo "... centralserver_automoc"
	@echo "... application_automoc"
	@echo "... ApplicationStart.o"
	@echo "... ApplicationStart.i"
	@echo "... ApplicationStart.s"
	@echo "... AuthenticationServer.o"
	@echo "... AuthenticationServer.i"
	@echo "... AuthenticationServer.s"
	@echo "... CustomObjects/CustomBool.o"
	@echo "... CustomObjects/CustomBool.i"
	@echo "... CustomObjects/CustomBool.s"
	@echo "... CustomObjects/CustomInt.o"
	@echo "... CustomObjects/CustomInt.i"
	@echo "... CustomObjects/CustomInt.s"
	@echo "... CustomObjects/CustomMap.o"
	@echo "... CustomObjects/CustomMap.i"
	@echo "... CustomObjects/CustomMap.s"
	@echo "... CustomObjects/CustomString.o"
	@echo "... CustomObjects/CustomString.i"
	@echo "... CustomObjects/CustomString.s"
	@echo "... CustomObjects/CustomVector.o"
	@echo "... CustomObjects/CustomVector.i"
	@echo "... CustomObjects/CustomVector.s"
	@echo "... Database/DatabaseHandler.o"
	@echo "... Database/DatabaseHandler.i"
	@echo "... Database/DatabaseHandler.s"
	@echo "... Marshalling/MarshalledMessage.o"
	@echo "... Marshalling/MarshalledMessage.i"
	@echo "... Marshalling/MarshalledMessage.s"
	@echo "... Marshalling/MarshallingManager.o"
	@echo "... Marshalling/MarshallingManager.i"
	@echo "... Marshalling/MarshallingManager.s"
	@echo "... Pages/HomePage.o"
	@echo "... Pages/HomePage.i"
	@echo "... Pages/HomePage.s"
	@echo "... Pages/LoginPage.o"
	@echo "... Pages/LoginPage.i"
	@echo "... Pages/LoginPage.s"
	@echo "... RPC/RpcCallsAuthServer.o"
	@echo "... RPC/RpcCallsAuthServer.i"
	@echo "... RPC/RpcCallsAuthServer.s"
	@echo "... RPC/RpcCallsClient.o"
	@echo "... RPC/RpcCallsClient.i"
	@echo "... RPC/RpcCallsClient.s"
	@echo "... RPC/RpcCallsServer.o"
	@echo "... RPC/RpcCallsServer.i"
	@echo "... RPC/RpcCallsServer.s"
	@echo "... RPC/RpcStubAuthServer.o"
	@echo "... RPC/RpcStubAuthServer.i"
	@echo "... RPC/RpcStubAuthServer.s"
	@echo "... RPC/RpcStubServer.o"
	@echo "... RPC/RpcStubServer.i"
	@echo "... RPC/RpcStubServer.s"
	@echo "... RequestHandler.o"
	@echo "... RequestHandler.i"
	@echo "... RequestHandler.s"
	@echo "... Stegnography/Paths.o"
	@echo "... Stegnography/Paths.i"
	@echo "... Stegnography/Paths.s"
	@echo "... Stegnography/StegManager.o"
	@echo "... Stegnography/StegManager.i"
	@echo "... Stegnography/StegManager.s"
	@echo "... UDPLayer/Message.o"
	@echo "... UDPLayer/Message.i"
	@echo "... UDPLayer/Message.s"
	@echo "... UDPLayer/MySocket.o"
	@echo "... UDPLayer/MySocket.i"
	@echo "... UDPLayer/MySocket.s"
	@echo "... UDPLayer/UDPSocket.o"
	@echo "... UDPLayer/UDPSocket.i"
	@echo "... UDPLayer/UDPSocket.s"
	@echo "... application_automoc.o"
	@echo "... application_automoc.i"
	@echo "... application_automoc.s"
	@echo "... centralserver_automoc.o"
	@echo "... centralserver_automoc.i"
	@echo "... centralserver_automoc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

