# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/omar_nawawy/Downloads/dist/distributed_2.1.1.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/omar_nawawy/Downloads/dist/distributed_2.1.1.1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/omar_nawawy/Downloads/dist/distributed_2.1.1.1/CMakeFiles /home/omar_nawawy/Downloads/dist/distributed_2.1.1.1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/omar_nawawy/Downloads/dist/distributed_2.1.1.1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

CustomObjects/CustomBool.o: CustomObjects/CustomBool.cpp.o

.PHONY : CustomObjects/CustomBool.o

# target to build an object file
CustomObjects/CustomBool.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomBool.cpp.o
.PHONY : CustomObjects/CustomBool.cpp.o

CustomObjects/CustomBool.i: CustomObjects/CustomBool.cpp.i

.PHONY : CustomObjects/CustomBool.i

# target to preprocess a source file
CustomObjects/CustomBool.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomBool.cpp.i
.PHONY : CustomObjects/CustomBool.cpp.i

CustomObjects/CustomBool.s: CustomObjects/CustomBool.cpp.s

.PHONY : CustomObjects/CustomBool.s

# target to generate assembly for a file
CustomObjects/CustomBool.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomBool.cpp.s
.PHONY : CustomObjects/CustomBool.cpp.s

CustomObjects/CustomInt.o: CustomObjects/CustomInt.cpp.o

.PHONY : CustomObjects/CustomInt.o

# target to build an object file
CustomObjects/CustomInt.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomInt.cpp.o
.PHONY : CustomObjects/CustomInt.cpp.o

CustomObjects/CustomInt.i: CustomObjects/CustomInt.cpp.i

.PHONY : CustomObjects/CustomInt.i

# target to preprocess a source file
CustomObjects/CustomInt.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomInt.cpp.i
.PHONY : CustomObjects/CustomInt.cpp.i

CustomObjects/CustomInt.s: CustomObjects/CustomInt.cpp.s

.PHONY : CustomObjects/CustomInt.s

# target to generate assembly for a file
CustomObjects/CustomInt.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomInt.cpp.s
.PHONY : CustomObjects/CustomInt.cpp.s

CustomObjects/CustomMap.o: CustomObjects/CustomMap.cpp.o

.PHONY : CustomObjects/CustomMap.o

# target to build an object file
CustomObjects/CustomMap.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomMap.cpp.o
.PHONY : CustomObjects/CustomMap.cpp.o

CustomObjects/CustomMap.i: CustomObjects/CustomMap.cpp.i

.PHONY : CustomObjects/CustomMap.i

# target to preprocess a source file
CustomObjects/CustomMap.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomMap.cpp.i
.PHONY : CustomObjects/CustomMap.cpp.i

CustomObjects/CustomMap.s: CustomObjects/CustomMap.cpp.s

.PHONY : CustomObjects/CustomMap.s

# target to generate assembly for a file
CustomObjects/CustomMap.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomMap.cpp.s
.PHONY : CustomObjects/CustomMap.cpp.s

CustomObjects/CustomString.o: CustomObjects/CustomString.cpp.o

.PHONY : CustomObjects/CustomString.o

# target to build an object file
CustomObjects/CustomString.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomString.cpp.o
.PHONY : CustomObjects/CustomString.cpp.o

CustomObjects/CustomString.i: CustomObjects/CustomString.cpp.i

.PHONY : CustomObjects/CustomString.i

# target to preprocess a source file
CustomObjects/CustomString.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomString.cpp.i
.PHONY : CustomObjects/CustomString.cpp.i

CustomObjects/CustomString.s: CustomObjects/CustomString.cpp.s

.PHONY : CustomObjects/CustomString.s

# target to generate assembly for a file
CustomObjects/CustomString.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomString.cpp.s
.PHONY : CustomObjects/CustomString.cpp.s

CustomObjects/CustomVector.o: CustomObjects/CustomVector.cpp.o

.PHONY : CustomObjects/CustomVector.o

# target to build an object file
CustomObjects/CustomVector.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomVector.cpp.o
.PHONY : CustomObjects/CustomVector.cpp.o

CustomObjects/CustomVector.i: CustomObjects/CustomVector.cpp.i

.PHONY : CustomObjects/CustomVector.i

# target to preprocess a source file
CustomObjects/CustomVector.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomVector.cpp.i
.PHONY : CustomObjects/CustomVector.cpp.i

CustomObjects/CustomVector.s: CustomObjects/CustomVector.cpp.s

.PHONY : CustomObjects/CustomVector.s

# target to generate assembly for a file
CustomObjects/CustomVector.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/CustomObjects/CustomVector.cpp.s
.PHONY : CustomObjects/CustomVector.cpp.s

Marshalling/MarshalledMessage.o: Marshalling/MarshalledMessage.cpp.o

.PHONY : Marshalling/MarshalledMessage.o

# target to build an object file
Marshalling/MarshalledMessage.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Marshalling/MarshalledMessage.cpp.o
.PHONY : Marshalling/MarshalledMessage.cpp.o

Marshalling/MarshalledMessage.i: Marshalling/MarshalledMessage.cpp.i

.PHONY : Marshalling/MarshalledMessage.i

# target to preprocess a source file
Marshalling/MarshalledMessage.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Marshalling/MarshalledMessage.cpp.i
.PHONY : Marshalling/MarshalledMessage.cpp.i

Marshalling/MarshalledMessage.s: Marshalling/MarshalledMessage.cpp.s

.PHONY : Marshalling/MarshalledMessage.s

# target to generate assembly for a file
Marshalling/MarshalledMessage.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Marshalling/MarshalledMessage.cpp.s
.PHONY : Marshalling/MarshalledMessage.cpp.s

Marshalling/MarshallingManager.o: Marshalling/MarshallingManager.cpp.o

.PHONY : Marshalling/MarshallingManager.o

# target to build an object file
Marshalling/MarshallingManager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Marshalling/MarshallingManager.cpp.o
.PHONY : Marshalling/MarshallingManager.cpp.o

Marshalling/MarshallingManager.i: Marshalling/MarshallingManager.cpp.i

.PHONY : Marshalling/MarshallingManager.i

# target to preprocess a source file
Marshalling/MarshallingManager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Marshalling/MarshallingManager.cpp.i
.PHONY : Marshalling/MarshallingManager.cpp.i

Marshalling/MarshallingManager.s: Marshalling/MarshallingManager.cpp.s

.PHONY : Marshalling/MarshallingManager.s

# target to generate assembly for a file
Marshalling/MarshallingManager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Marshalling/MarshallingManager.cpp.s
.PHONY : Marshalling/MarshallingManager.cpp.s

Message.o: Message.cpp.o

.PHONY : Message.o

# target to build an object file
Message.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Message.cpp.o
.PHONY : Message.cpp.o

Message.i: Message.cpp.i

.PHONY : Message.i

# target to preprocess a source file
Message.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Message.cpp.i
.PHONY : Message.cpp.i

Message.s: Message.cpp.s

.PHONY : Message.s

# target to generate assembly for a file
Message.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Message.cpp.s
.PHONY : Message.cpp.s

MySocket.o: MySocket.cpp.o

.PHONY : MySocket.o

# target to build an object file
MySocket.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/MySocket.cpp.o
.PHONY : MySocket.cpp.o

MySocket.i: MySocket.cpp.i

.PHONY : MySocket.i

# target to preprocess a source file
MySocket.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/MySocket.cpp.i
.PHONY : MySocket.cpp.i

MySocket.s: MySocket.cpp.s

.PHONY : MySocket.s

# target to generate assembly for a file
MySocket.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/MySocket.cpp.s
.PHONY : MySocket.cpp.s

RPC.o: RPC.cpp.o

.PHONY : RPC.o

# target to build an object file
RPC.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RPC.cpp.o
.PHONY : RPC.cpp.o

RPC.i: RPC.cpp.i

.PHONY : RPC.i

# target to preprocess a source file
RPC.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RPC.cpp.i
.PHONY : RPC.cpp.i

RPC.s: RPC.cpp.s

.PHONY : RPC.s

# target to generate assembly for a file
RPC.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RPC.cpp.s
.PHONY : RPC.cpp.s

RPCStub.o: RPCStub.cpp.o

.PHONY : RPCStub.o

# target to build an object file
RPCStub.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RPCStub.cpp.o
.PHONY : RPCStub.cpp.o

RPCStub.i: RPCStub.cpp.i

.PHONY : RPCStub.i

# target to preprocess a source file
RPCStub.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RPCStub.cpp.i
.PHONY : RPCStub.cpp.i

RPCStub.s: RPCStub.cpp.s

.PHONY : RPCStub.s

# target to generate assembly for a file
RPCStub.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RPCStub.cpp.s
.PHONY : RPCStub.cpp.s

RequestHandler.o: RequestHandler.cpp.o

.PHONY : RequestHandler.o

# target to build an object file
RequestHandler.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RequestHandler.cpp.o
.PHONY : RequestHandler.cpp.o

RequestHandler.i: RequestHandler.cpp.i

.PHONY : RequestHandler.i

# target to preprocess a source file
RequestHandler.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RequestHandler.cpp.i
.PHONY : RequestHandler.cpp.i

RequestHandler.s: RequestHandler.cpp.s

.PHONY : RequestHandler.s

# target to generate assembly for a file
RequestHandler.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/RequestHandler.cpp.s
.PHONY : RequestHandler.cpp.s

UDPSocket.o: UDPSocket.cpp.o

.PHONY : UDPSocket.o

# target to build an object file
UDPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/UDPSocket.cpp.o
.PHONY : UDPSocket.cpp.o

UDPSocket.i: UDPSocket.cpp.i

.PHONY : UDPSocket.i

# target to preprocess a source file
UDPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/UDPSocket.cpp.i
.PHONY : UDPSocket.cpp.i

UDPSocket.s: UDPSocket.cpp.s

.PHONY : UDPSocket.s

# target to generate assembly for a file
UDPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/UDPSocket.cpp.s
.PHONY : UDPSocket.cpp.s

test_callrpc.o: test_callrpc.cpp.o

.PHONY : test_callrpc.o

# target to build an object file
test_callrpc.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/test_callrpc.cpp.o
.PHONY : test_callrpc.cpp.o

test_callrpc.i: test_callrpc.cpp.i

.PHONY : test_callrpc.i

# target to preprocess a source file
test_callrpc.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/test_callrpc.cpp.i
.PHONY : test_callrpc.cpp.i

test_callrpc.s: test_callrpc.cpp.s

.PHONY : test_callrpc.s

# target to generate assembly for a file
test_callrpc.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/test_callrpc.cpp.s
.PHONY : test_callrpc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... CustomObjects/CustomBool.o"
	@echo "... CustomObjects/CustomBool.i"
	@echo "... CustomObjects/CustomBool.s"
	@echo "... CustomObjects/CustomInt.o"
	@echo "... CustomObjects/CustomInt.i"
	@echo "... CustomObjects/CustomInt.s"
	@echo "... CustomObjects/CustomMap.o"
	@echo "... CustomObjects/CustomMap.i"
	@echo "... CustomObjects/CustomMap.s"
	@echo "... CustomObjects/CustomString.o"
	@echo "... CustomObjects/CustomString.i"
	@echo "... CustomObjects/CustomString.s"
	@echo "... CustomObjects/CustomVector.o"
	@echo "... CustomObjects/CustomVector.i"
	@echo "... CustomObjects/CustomVector.s"
	@echo "... Marshalling/MarshalledMessage.o"
	@echo "... Marshalling/MarshalledMessage.i"
	@echo "... Marshalling/MarshalledMessage.s"
	@echo "... Marshalling/MarshallingManager.o"
	@echo "... Marshalling/MarshallingManager.i"
	@echo "... Marshalling/MarshallingManager.s"
	@echo "... Message.o"
	@echo "... Message.i"
	@echo "... Message.s"
	@echo "... MySocket.o"
	@echo "... MySocket.i"
	@echo "... MySocket.s"
	@echo "... RPC.o"
	@echo "... RPC.i"
	@echo "... RPC.s"
	@echo "... RPCStub.o"
	@echo "... RPCStub.i"
	@echo "... RPCStub.s"
	@echo "... RequestHandler.o"
	@echo "... RequestHandler.i"
	@echo "... RequestHandler.s"
	@echo "... UDPSocket.o"
	@echo "... UDPSocket.i"
	@echo "... UDPSocket.s"
	@echo "... test_callrpc.o"
	@echo "... test_callrpc.i"
	@echo "... test_callrpc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

